# Generated by Django 5.1.4 on 2025-01-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_document_delete_uploadedfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='document',
            name='file_size',
            field=models.IntegerField(null=True),
        ),
    ]
