# Generated by Django 5.1.4 on 2025-01-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_work_delete_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='file_size',
        ),
    ]
