# Generated by Django 5.1.4 on 2025-01-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_work_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='file_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
