# Generated by Django 5.1.4 on 2025-02-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='job',
            field=models.TextField(default='Ph. D.'),
        ),
    ]
