# Generated by Django 5.1.4 on 2025-02-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_user_data_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='job',
            field=models.TextField(),
        ),
    ]
