# Generated by Django 5.1.4 on 2025-02-05 09:16

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_user_data_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='avatar',
            field=models.FileField(default='avatars/default.png', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='country',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='firstname',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='job',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='language',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='lastname',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
