# Generated by Django 5.1.4 on 2025-02-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_user_data_avatar_alter_user_data_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='avatar',
            field=models.FileField(default='avatars/default.png', upload_to='avatars/'),
        ),
    ]
