# Generated by Django 5.1.4 on 2025-02-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_user_data_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='avatar',
            field=models.FileField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/'),
        ),
    ]
