# Generated by Django 5.1.4 on 2025-02-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_user_data_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='status',
            field=models.TextField(default='send'),
        ),
    ]
