# Generated by Django 5.1.4 on 2025-02-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_work_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('send', 'Send'), ('review', 'Review'), ('accept', 'Accept')], default='Send', max_length=15),
        ),
    ]
