# Generated by Django 5.1.4 on 2025-03-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rewiev_work_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_role',
            old_name='role',
            new_name='user_role',
        ),
    ]
