# Generated by Django 5.1.4 on 2025-03-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_rename_role_user_role_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_role',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('reviewer', 'Reviewer'), ('user', 'User')], default='User', max_length=8),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
