# Generated by Django 5.1.4 on 2025-03-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_user_role_user_role_alter_work_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.TextField(max_length=80, unique=True),
        ),
    ]
