# Generated by Django 5.1.4 on 2025-03-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_work_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
