# Generated by Django 5.1.4 on 2025-03-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_review_work_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review_work',
            old_name='user',
            new_name='user_id',
        ),
    ]
