# Generated by Django 5.1.4 on 2025-03-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_rename_user_review_work_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review_work',
            old_name='user_id',
            new_name='users',
        ),
    ]
