# Generated by Django 5.1.4 on 2025-03-31 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_review_work_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_work',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.work'),
        ),
    ]
