# Generated by Django 5.1.4 on 2025-04-01 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_review_work_work'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_work',
            name='users',
        ),
        migrations.AddField(
            model_name='review_work',
            name='description',
            field=models.TextField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='review_work',
            name='seq',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review_work',
            name='status',
            field=models.CharField(choices=[('send', 'Send'), ('review', 'Review'), ('accept', 'Accept'), ('refuse', 'Refuse'), ('finalise', 'Finalise')], default='Send', max_length=15),
        ),
        migrations.AddField(
            model_name='review_work',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('send', 'Send'), ('review', 'Review'), ('accept', 'Accept'), ('refuse', 'Refuse'), ('finalise', 'Finalise')], default='Send', max_length=15),
        ),
    ]
