# Generated by Django 5.1.4 on 2025-04-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_remove_review_work_users_review_work_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_work',
            name='send_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
