# Generated by Django 5.1.4 on 2025-04-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_review_work_send_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='email_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('unsubmitted', 'Unsubmitted')], default='unsubmitted', max_length=11),
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('send', 'Send'), ('review', 'Review'), ('accept', 'Accept'), ('refuse', 'Refuse'), ('finalise', 'Finalise')], default='send', max_length=15),
        ),
    ]
