# Generated by Django 5.1.4 on 2025-04-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_work_email_status_alter_work_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='email_status',
            field=models.CharField(choices=[('sub', 'Submitted'), ('unsub', 'Unsubmitted')], default='unsubmitted', max_length=11),
        ),
    ]
