# Generated by Django 5.1.4 on 2025-04-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_work_email_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_work',
            name='seq',
        ),
    ]
